# Generated by Django 5.2 on 2025-04-10 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_precioenergia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroconsumo',
            name='precio_kwh_mes',
            field=models.FloatField(blank=True, help_text='Precio del kWh según el recibo mensual (en COP)', null=True),
        ),
    ]
