# Generated by Django 5.2 on 2025-04-10 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_registroconsumo_precio_kwh_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroconsumo',
            name='precio_kwh_mes',
            field=models.FloatField(blank=True, help_text='Precio del kWh según el promedio mensual (en COP)', null=True),
        ),
    ]
