# Generated by Django 5.2 on 2025-04-16 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_registroconsumo_precio_kwh_mes'),
    ]

    operations = [
        migrations.CreateModel(
            name='MesActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('anio', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('mes', 'anio')},
            },
        ),
    ]
