# Generated by Django 5.2 on 2025-04-16 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_mesactivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precioenergia',
            name='fecha_registro',
            field=models.DateField(unique=True),
        ),
    ]
