# Generated by Django 5.2 on 2025-04-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_precioenergia_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinaria',
            name='corriente',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maquinaria',
            name='potencia_watts',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='maquinaria',
            name='voltaje',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
