# Generated by Django 5.2 on 2025-04-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_maquinaria_corriente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinaria',
            name='potencia_watts',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
