# Generated by Django 5.2 on 2025-04-28 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_maquinaria_potencia_watts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mesactivo',
            old_name='anio',
            new_name='año',
        ),
        migrations.AlterUniqueTogether(
            name='mesactivo',
            unique_together={('mes', 'año')},
        ),
    ]
