# Generated by Django 5.2 on 2025-04-28 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_anio_mesactivo_año_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moldemaquinariaasignacion',
            name='molde',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='core.molde'),
        ),
    ]
